package com.nearsoft.ws.groovy
/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'jresendiz' at '3/20/17 6:14 PM' with Gradle 3.0
 *
 * @author jresendiz, @date 3/20/17 6:14 PM
 */
class CollectionsExamples {

    def countAllArtistsFromJson() {
        return -1;
    }

    def countAllArtistsFromXMl() {
        return -1
    }

    List<String> getArtistsNamesFromJson() {
        return []
    }

    List<String> getArtistsNamesFromXML() {
        return []
    }

    File getGenerateCSVFile() {
        return null;
    }
}
